CREATE TABLE IF NOT EXISTS profiles (channel TEXT PRIMARY KEY, handle TEXT NOT NULL, avatar_key TEXT NOT NULL, title TEXT NOT NULL, token_hash TEXT NOT NULL, gif TEXT, updated INTEGER NOT NULL, verified INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS profiles_handle ON profiles(handle);
CREATE TABLE IF NOT EXISTS challenges (secret_hash TEXT PRIMARY KEY, channel TEXT NOT NULL, proof TEXT NOT NULL, expires INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS reports (channel TEXT PRIMARY KEY, count INTEGER NOT NULL DEFAULT 1, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS blocked (channel TEXT PRIMARY KEY);
