import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{ref,validateGif,avatarKey} from './worker.mjs';
const id='UCabcdefghijklmnopqrstuv',other='UC'+'z'.repeat(22);
const gif='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
class D1{constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));}prepare(sql){const db=this.db;let args=[];return {bind(...values){args=values;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}};}async batch(queries){this.db.exec('BEGIN');try{const r=[];for(const q of queries)r.push(await q.run());this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}}
test('channel parsing and GIF validation reject unrelated URLs and invalid media',()=>{assert.equal(ref('https://www.youtube.com/@Crystal-28828'),'@crystal-28828');assert.equal(ref(id),id);assert.throws(()=>ref('https://evil.test/@crystal'));assert.throws(()=>ref('@ab'));assert.equal(validateGif(gif),gif);assert.throws(()=>validateGif('data:text/html;base64,PGgxPg=='));assert.equal(avatarKey('https://yt3.ggpht.com/unique=s88'),'/unique');assert.equal(avatarKey('https://yt3.googleusercontent.com/unique=s176'),'/unique');assert.equal(avatarKey('https://evil.test/unique'),'');});
test('verified publishing, two-viewer lookup, token protection, replay rejection, removal',async()=>{const env={DB:new D1(),YOUTUBE_API_KEY:'test',ADMIN_TOKEN:'test-admin'};let description='';const originalFetch=globalThis.fetch;globalThis.fetch=async u=>{assert.equal(new URL(u).origin,'https://www.googleapis.com');return new Response(JSON.stringify({items:[{id,snippet:{title:'Demo',customUrl:'@demo',description,thumbnails:{default:{url:'https://yt3.ggpht.com/demo=s88'}}}}]}));};
async function call(path,method='GET',data,token){const response=await worker.fetch(new Request('https://service.test'+path,{method,headers:{'CF-Connecting-IP':'1.2.3.4',...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined}),env);return {status:response.status,data:response.headers.get('Content-Type')==='image/gif'?await response.arrayBuffer():await response.json()};}
try{assert.equal((await call('/profile','PUT',{gif})).status,401);const c=await call('/challenge','POST',{channel:'@demo'});assert.equal(c.status,200);assert.equal((await call('/verify','POST',{secret:c.data.secret})).status,400);description=c.data.proof;const verified=await call('/verify','POST',{secret:c.data.secret});assert.equal(verified.status,200);assert.equal(verified.data.channel,id);assert.equal((await call('/verify','POST',{secret:c.data.secret})).status,401);assert.equal((await call('/profile','PUT',{gif},'0'.repeat(48))).status,401);assert.equal((await call('/profile','PUT',{gif},verified.data.token)).status,200);const a=await call('/lookup','POST',{refs:[id]});const b=await call('/lookup','POST',{refs:['@demo',other]});assert.equal(a.data.profiles[0].channel,id);assert.equal(b.data.profiles.length,1);assert.equal('token_hash' in a.data.profiles[0],false);assert.equal((await call('/avatar/'+id)).status,200);assert.equal((await call('/profile','DELETE',undefined,'0'.repeat(48))).status,401);assert.equal((await call('/profile','DELETE',undefined,verified.data.token)).status,200);assert.deepEqual((await call('/lookup','POST',{refs:[id]})).data.profiles,[]);assert.equal((await call('/avatar/'+id)).status,404);}finally{globalThis.fetch=originalFetch;}});
test('oversized lookups, missing verification setup, rate limits',async()=>{const env={DB:new D1()};async function call(path,data){return worker.fetch(new Request('https://service.test'+path,{method:'POST',body:JSON.stringify(data)}),env);}assert.equal((await call('/lookup',{refs:Array(41).fill(id)})).status,400);assert.equal((await call('/challenge',{channel:id})).status,503);for(let i=0;i<120;i++)await call('/lookup',{refs:[]});assert.equal((await call('/lookup',{refs:[]})).status,429);});

test('community GIF limit accepts 1 MB and rejects larger files',()=>{const make=n=>{const bytes=new Uint8Array(n);bytes.set(new TextEncoder().encode('GIF89a'),0);bytes[6]=1;bytes[8]=1;bytes[n-1]=0x3b;return 'data:image/gif;base64,'+Buffer.from(bytes).toString('base64');};assert.equal(validateGif(make(1048576)).length>0,true);assert.throws(()=>validateGif(make(1048577)));});