const DAY=86400,MAX=524288;
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const now=()=>Math.floor(Date.now()/1000);
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');
export const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
export function avatarKey(src){try{let u=new URL(src);if(!/(^|\.)(ggpht\.com|googleusercontent\.com)$/.test(u.hostname))return '';return u.hostname+u.pathname.replace(/=.+$/,'');}catch{return '';}}
export function ref(value){if(typeof value!=='string'||value.length>200)fail('Enter a YouTube @handle or channel ID.');let s=value.trim();if(s.startsWith('https://')){const u=new URL(s);if(!['www.youtube.com','youtube.com'].includes(u.hostname))fail('Use a YouTube channel link.');s=decodeURIComponent(u.pathname).replace(/^\/(channel\/)?/,'').replace(/\/$/,'');}if(/^UC[\w-]{22}$/.test(s))return s;if(/^@[^\s/?#]{3,100}$/u.test(s))return s.toLowerCase();fail('Enter a YouTube @handle or channel ID.');}
export function validateGif(data){if(typeof data!=='string'||!/^data:image\/gif;base64,[A-Za-z0-9+/]+=*$/.test(data)||data.length>MAX*4/3+100)fail('Choose a GIF no larger than 512 KB.');let bytes;try{bytes=Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0));}catch{fail('Invalid GIF.');}if(bytes.length>MAX||bytes.length<14||!['GIF87a','GIF89a'].includes(String.fromCharCode(...bytes.slice(0,6))))fail('Invalid GIF.');const width=bytes[6]|bytes[7]<<8,height=bytes[8]|bytes[9]<<8;if(!width||!height||width>512||height>512)fail('Shared GIFs must be 512 × 512 pixels or smaller.');if(bytes.at(-1)!==0x3b)fail('Incomplete GIF file.');return data;}
async function body(req){const reader=req.body?.getReader();if(!reader)fail('Missing request body.');let count=0,parts=[];while(true){let {done,value}=await reader.read();if(done)break;count+=value.length;if(count>MAX*1.4+4096){await reader.cancel();fail('Request too large.',413);}parts.push(value);}const all=new Uint8Array(count);let offset=0;for(const p of parts){all.set(p,offset);offset+=p.length;}try{return JSON.parse(new TextDecoder().decode(all));}catch{fail('Invalid JSON.');}}
async function limit(env,key,max,ttl){const bucket=key+':'+Math.floor(now()/ttl);const row=await env.DB.prepare('INSERT INTO limits(bucket,count,expires) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,now()+ttl*2).first();if(row.count>max)fail('Too many requests. Please try again later.',429);}
async function channel(env,reference){if(!env.YOUTUBE_API_KEY)fail('Channel verification is not configured yet.',503);await limit(env,'youtube-quota',4000,DAY);const u=new URL('https://www.googleapis.com/youtube/v3/channels');u.searchParams.set('part','snippet');u.searchParams.set(reference.startsWith('@')?'forHandle':'id',reference);u.searchParams.set('key',env.YOUTUBE_API_KEY);const res=await fetch(u,{signal:AbortSignal.timeout(12000)});if(!res.ok)fail('YouTube verification is unavailable. Try again later.',503);const data=await res.json(),c=data.items?.[0];if(!c)fail('YouTube channel not found.',404);return c;}
async function auth(req,env){const token=req.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token||!/^[a-f0-9]{48}$/.test(token))fail('Verify your channel first.',401);const p=await env.DB.prepare('SELECT * FROM profiles WHERE token_hash=?').bind(await hash(token)).first();if(!p)fail('Session expired. Verify your channel again.',401);return p;}
async function isBlocked(env,id){return await env.DB.prepare('SELECT channel FROM blocked WHERE channel=?').bind(id).first();}
async function route(req,env){const url=new URL(req.url),path=url.pathname;
if(path==='/health')return json({service:'crystal-shared-pfp',version:2,verificationConfigured:!!env.YOUTUBE_API_KEY});
if(path==='/privacy'||path==='/')return new Response(PRIVACY,{headers:{'Content-Type':'text/html;charset=utf-8','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'",'X-Content-Type-Options':'nosniff'}});
if(!env.DB)fail('Service database is not configured.',503);
const ip=req.headers.get('CF-Connecting-IP')||'local';
if(req.method==='GET'&&/^\/avatar\/UC[\w-]{22}$/.test(path)){const id=path.split('/')[2];const p=await env.DB.prepare('SELECT gif,verified FROM profiles WHERE channel=? AND gif IS NOT NULL AND channel NOT IN (SELECT channel FROM blocked)').bind(id).first();if(!p||p.verified<now()-30*DAY)fail('No shared GIF.',404);const bytes=Uint8Array.from(atob(p.gif.split(',')[1]),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':'image/gif','Cache-Control':'public,max-age=60','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}
if(req.method==='POST'&&path==='/lookup'){await limit(env,'lookup:'+await hash(ip),120,60);const b=await body(req);if(!Array.isArray(b.refs)||b.refs.length>40)fail('At most 40 channels per lookup.');const refs=[...new Set(b.refs.map(ref))];if(!refs.length)return json({profiles:[]});const marks=refs.map(()=>'?').join(',');const {results}=await env.DB.prepare(`SELECT channel,handle,avatar_key,updated FROM profiles WHERE (channel IN (${marks}) OR handle IN (${marks})) AND gif IS NOT NULL AND verified>? AND channel NOT IN (SELECT channel FROM blocked)`).bind(...refs,...refs,now()-30*DAY).all();return json({profiles:results});}
if(req.method==='POST'&&path==='/challenge'){await limit(env,'challenge:'+await hash(ip),8,3600);const b=await body(req),c=await channel(env,ref(b.channel));if(await isBlocked(env,c.id))fail('This channel cannot publish shared GIFs.',403);const secret=random(),proof='CRYSTAL-PFP-'+random();await env.DB.prepare('INSERT INTO challenges(secret_hash,channel,proof,expires) VALUES(?,?,?,?)').bind(await hash(secret),c.id,proof,now()+3600).run();return json({secret,proof,channel:c.id,title:c.snippet.title,expires:now()+3600});}
if(req.method==='POST'&&path==='/verify'){await limit(env,'verify:'+await hash(ip),20,3600);const b=await body(req);if(typeof b.secret!=='string'||!/^[a-f0-9]{48}$/.test(b.secret))fail('Start verification again.');const digest=await hash(b.secret);const challenge=await env.DB.prepare('UPDATE challenges SET attempts=attempts+1 WHERE secret_hash=? AND expires>? AND attempts<10 RETURNING *').bind(digest,now()).first();if(!challenge)fail('Verification expired. Start again.',401);const c=await channel(env,challenge.channel);if(!c.snippet.description?.includes(challenge.proof))fail('Code not found in your public channel description yet. Save it in YouTube Studio, wait a minute, then retry.');if(await isBlocked(env,c.id))fail('This channel cannot publish shared GIFs.',403);const handle=(c.snippet.customUrl||'').toLowerCase(),ak=avatarKey(c.snippet.thumbnails?.default?.url||'');if(!ak)fail('Could not read the channel picture.');const token=random();
// Atomically consume the challenge and issue credentials. Replays cannot rotate a token.
await env.DB.batch([env.DB.prepare('INSERT INTO profiles(channel,handle,avatar_key,title,token_hash,updated,verified) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM challenges WHERE secret_hash=? AND expires>?) ON CONFLICT(channel) DO UPDATE SET handle=excluded.handle,avatar_key=excluded.avatar_key,title=excluded.title,token_hash=excluded.token_hash,verified=excluded.verified').bind(c.id,handle,ak,c.snippet.title,await hash(token),now(),now(),digest,now()),env.DB.prepare('DELETE FROM challenges WHERE secret_hash=?').bind(digest)]);
const saved=await env.DB.prepare('SELECT token_hash FROM profiles WHERE channel=?').bind(c.id).first();if(saved?.token_hash!==await hash(token))fail('Verification already used. Start again.',409);return json({token,channel:c.id,title:c.snippet.title,handle});}
if(req.method==='PUT'&&path==='/profile'){await limit(env,'publish:'+await hash(ip),30,3600);const p=await auth(req,env);if(p.verified<now()-30*DAY)fail('Verify your channel again to renew sharing.',401);if(await isBlocked(env,p.channel))fail('Publishing is disabled for this channel.',403);const b=await body(req);validateGif(b.gif);await env.DB.prepare('UPDATE profiles SET gif=?,updated=? WHERE channel=? AND token_hash=?').bind(b.gif,now(),p.channel,p.token_hash).run();return json({published:true,channel:p.channel});}
if(req.method==='DELETE'&&path==='/profile'){const p=await auth(req,env);await env.DB.prepare('DELETE FROM profiles WHERE channel=? AND token_hash=?').bind(p.channel,p.token_hash).run();return json({deleted:true});}
if(req.method==='POST'&&path==='/report'){await limit(env,'report:'+await hash(ip),5,3600);const b=await body(req),id=ref(b.channel);if(id.startsWith('@'))fail('Use a channel ID.');await env.DB.prepare('INSERT INTO reports(channel,updated) VALUES(?,?) ON CONFLICT(channel) DO UPDATE SET count=count+1,updated=excluded.updated').bind(id,now()).run();return json({reported:true});}
if(path==='/admin/reports'||path==='/admin/block'){if(!env.ADMIN_TOKEN||req.headers.get('Authorization')!=='Bearer '+env.ADMIN_TOKEN)fail('Unauthorized.',401);if(path==='/admin/reports'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM reports ORDER BY updated DESC LIMIT 100').all();return json(rows);}if(path==='/admin/block'&&req.method==='POST'){const b=await body(req),id=ref(b.channel);if(id.startsWith('@'))fail('Use a channel ID.');await env.DB.batch([env.DB.prepare('INSERT OR IGNORE INTO blocked(channel) VALUES(?)').bind(id),env.DB.prepare('DELETE FROM profiles WHERE channel=?').bind(id),env.DB.prepare('DELETE FROM reports WHERE channel=?').bind(id)]);return json({blocked:true});}}
fail('Not found.',404);}
const PRIVACY=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Crystal GIF PFP — Privacy</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:17px/1.7 system-ui;background:#14111d;color:#ece5f5}h1,h2{color:#c6a5ff}a{color:#c6a5ff}</style><h1>Crystal GIF PFP</h1><p>Shared animated pictures for people using the Crystal browser extension. Unaffiliated with Google or YouTube.</p><h2>Privacy and sharing</h2><p>Local mode keeps your GIF and selected image address in your Chrome profile. Shared mode is optional. When enabled, visible YouTube channel handles or IDs are sent to this service to find shared pictures. Full video URLs, video titles, comments, and watch history are not sent.</p><p>Publishing stores your uploaded GIF, verified public channel ID, handle, title, public avatar image key, timestamps, and a hashed management token. Published GIFs and channel associations are public and may be downloaded. Never upload private or sensitive material.</p><p>Verification reads your public channel description through YouTube's API to check a temporary code. Your YouTube password is never requested. Remove the code after verification. Verification must be renewed after 30 days. Expired profiles and their GIFs are removed by daily cleanup.</p><p>The service stores a hash of the connecting IP address in short-lived rate-limit buckets until daily cleanup (up to three days). Challenge records expire after one hour. Cloudflare and Google process requests under their own policies. No analytics, advertising, sale of data, or third-party GIF providers are used by this extension.</p><h2>Control and removal</h2><p>Use Delete shared profile in the extension to remove your public record and credentials. Cached GIFs can remain for up to five minutes; copies downloaded by others cannot be recalled. Uninstalling removes local settings but does not delete a published profile. Reverify your channel to recover management access.</p><p>You can disable shared pictures or block a specific channel locally. Use Report in the extension for abusive GIFs; reports store the channel ID, count, and timestamp for the operator. Reported content is not automatically removed. Only upload images you have permission to share.</p><p>Contact the publisher through the extension's Chrome Web Store support contact for privacy requests.</p></html>`;
export default {async fetch(req,env){try{return await route(req,env);}catch(e){return json({error:e.status?e.message:'Service temporarily unavailable.'},e.status||500);}},async scheduled(event,env){await env.DB.batch([env.DB.prepare('DELETE FROM challenges WHERE expires<?').bind(now()),env.DB.prepare('DELETE FROM limits WHERE expires<?').bind(now()),env.DB.prepare('DELETE FROM profiles WHERE verified<?').bind(now()-30*DAY)]);}};
